### ISSUE TITLE
Make the installation directions more explicit?

### ISSUE THREAD

**Issue by rodonn** [WizardMac/ReadStat.jl#10]
I think it might be helpful if the main README had explicit installation directions.

Here's what I did to get it working in OSX (using homebrew)

```
brew install ragel
git clone https://github.com/WizardMac/ReadStat.git
cd ReadStat
make
sudo make install
```

and then in julia

```
Pkg.clone("https://github.com/WizardMac/DataRead.jl.git")
```

I'm not sure if what I did is the simplest way to get it working.

**Comment by alstat** [comment]
It worked for me by simply running the following:
```
Pkg.clone(https://github.com/WizardMac/ReadStat.jl)
Pkg.build("ReadStat")
```
Tested on Windows 10.

**Comment by rodonn** [comment]
Awesome. That worked for me also.
