### ISSUE TITLE
Rename the package

### ISSUE THREAD

**Issue by davidanthoff** [WizardMac/ReadStat.jl#18]
I'm pretty sure the current name won't be accepted for registration in METADATA.jl, it seems way too generic to me. @tkelman probably has a better read on the rules there.

Maybe just name it ``ReadStat.jl``? Or go with something like the R package, ``Haven.jl``? I'm not suggesting the name ``Haven.jl``, given that it is already taken by the R package, more something like it. (Although, ``Haven.jl`` would make it very discoverable for people coming from R... But not sure how @hadley would feel about that).

**Comment by tkelman** [comment]
oh this isn't registered yet?

**Comment by hadley** [comment]
Generally, I think you should either re-use the library name everywhere, or have a unique name for each wrapper. Since I called it haven instead of ReadStat, I think that means you should call it something different for julia. Some ideas: habour, visa, refuge.

**Comment by tkelman** [comment]
The registration rules are pretty subjective, and while this name isn't that bad it is a bit generic and it's maybe slightly confusing that it doesn't mirror the name of the underlying library. Either way. Renaming after registration is a pain, renaming before is mostly sed and git mv.

**Comment by evanmiller** [comment]
I think `ReadStat.jl` makes the most sense.

**Comment by evanmiller** [comment]
Done
