### ISSUE TITLE
Function names

### ISSUE THREAD

**Issue by quantbabies** [WizardMac/ReadStat.jl#2]
DataRead.jl calls parse_sas7bdat.  This function doesn't exist in the ReadStat-master package. readstat_parse_sas7bdat does exist, but when the correct name is swapped in to line 130 of DataReal.jl the function read_sas7bdat("filpath.sas7bdat") returns an empty 0x0 DataFrame.

What version of readstat are you using?

**Comment by evanmiller** [comment]
The latest commits should fix this issue.
