### ISSUE TITLE
Tag and register in METADATA.jl

### ISSUE THREAD

**Issue by davidanthoff** [WizardMac/ReadStat.jl#20]

**Comment by davidanthoff** [comment]
@evanmiller Bump, any reason to not do this? This is such a useful package for lots of folks, and having it registered would make things a lot simpler for many.

The easiest way to do this is to enable attobot for this repo, see [here](https://github.com/attobot/attobot).

**Comment by evanmiller** [comment]
Okay, I installed attobot and created a release. I guess I wait for a PR now?

**Comment by davidanthoff** [comment]
You just wait until someone merges JuliaLang/METADATA.jl#8345. Typically there is some back and forth in that PR, especially with a new package registration. I'll monitor that PR on METADATA.jl as well.

**Comment by evanmiller** [comment]
Done

**Comment by davidanthoff** [comment]
Perfect, thanks!
