### ISSUE TITLE
Enable coveralls.io

### ISSUE THREAD

**Issue by davidanthoff** [WizardMac/ReadStat.jl#21]
@evanmiller the travis file should already submit coverage info to coveralls.io, so probably enough if you just switch it on at https://coveralls.io/.

**Comment by evanmiller** [comment]
What is the motivation here?

**Comment by davidanthoff** [comment]
It will tell us (and track) which lines are run by the tests and give an indication which parts of the code are not actually tested.

**Comment by evanmiller** [comment]
Ok, I've enabled it. Will add a badge to the README for kicks.

**Comment by davidanthoff** [comment]
Ha, there are only three lines that aren't covered by the tests :+1:
